(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now().toString(36);
const clone=o=>JSON.parse(JSON.stringify(o));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const initial=[
{id:"spawn",name:"SpawnLocation",type:"SpawnLocation",position:[0,1,0],rotation:[0,0,0],size:[2,1,2],color:"#22c55e",material:"Neon",anchored:true,canCollide:true,transparency:0,locked:false,visible:true,parent:null},
{id:"base",name:"Baseplate",type:"Part",position:[0,0,0],rotation:[0,0,0],size:[24,1,24],color:"#586174",material:"Plastic",anchored:true,canCollide:true,transparency:0,locked:false,visible:true,parent:null},
{id:"platform",name:"Platform",type:"Part",position:[0,3,-7],rotation:[0,0,0],size:[6,1,4],color:"#8b5cf6",material:"Plastic",anchored:true,canCollide:true,transparency:0,locked:false,visible:true,parent:null}
];
const S={nodes:clone(initial),selected:"base",tool:"select",panel:"properties",playing:false,project:"Meu Primeiro Jogo",grid:1,snap:true,history:[],future:[],sourceRbxl:null,playSnapshot:null,clipboard:null,settings:{theme:"dark",outline:true,autosave:true}};
let scene,camera,renderer,ray,pointer,target,theta=.62,phi=.92,radius=27,orbit=false,drag=false,lx=0,ly=0,meshes=new Map(),selectionBox,dragStart=null,editorGrid=null,simLast=0,simVelocity=new Map();
function status(t){$("#status").textContent=t;$("#footerStatus").textContent=t}
function toast(t){const d=document.createElement("div");d.className="toast";d.textContent=t;$("#toastRoot").appendChild(d);setTimeout(()=>d.remove(),2400)}
function cur(){return S.nodes.find(n=>n.id===S.selected)}
function commit(){S.history.push({nodes:clone(S.nodes),selected:S.selected,project:S.project});if(S.history.length>60)S.history.shift();S.future=[]}
function restore(s){S.nodes=clone(s.nodes);S.selected=s.selected;S.project=s.project;$("#projectName").value=S.project;render()}
function save(notify=true){try{localStorage.setItem("studio-lite-v4",JSON.stringify({name:S.project,nodes:S.nodes,settings:S.settings,grid:S.grid,snap:S.snap}));status("Salvo localmente");if(notify)toast("Projeto salvo neste dispositivo")}catch(err){console.error(err);status("Falha ao salvar");toast("Não foi possível salvar: armazenamento cheio ou bloqueado")}}
function undo(){if(!S.history.length)return toast("Nada para desfazer");S.future.push({nodes:clone(S.nodes),selected:S.selected,project:S.project});restore(S.history.pop());save(false);toast("Desfeito")}
function redo(){if(!S.future.length)return toast("Nada para refazer");S.history.push({nodes:clone(S.nodes),selected:S.selected,project:S.project});restore(S.future.pop());save(false);toast("Refeito")}
function add(type="Part"){commit();const p={Part:[[4,1,4],"#3b82f6","Plastic","box"],SpawnLocation:[[2,1,2],"#22c55e","Neon","box"],Folder:[[1,1,1],"#64748b","Plastic","box"],Script:[[1,1,1],"#64748b","Plastic","box"],Sphere:[[4,4,4],"#f59e0b","Plastic","sphere"],Cylinder:[[3,4,3],"#06b6d4","Metal","cylinder"],Wedge:[[4,3,4],"#ef4444","Plastic","wedge"]}[type]||[[4,1,4],"#3b82f6","Plastic","box"];const n={id:uid(),name:type,type,position:[0,2,0],rotation:[0,0,0],size:p[0].slice(),color:p[1],material:p[2],shape:p[3],anchored:true,canCollide:type!=="Folder"&&type!=="Script",transparency:0,locked:false,visible:true,parent:null};if(type==="Script")n.script='-- Novo Script\n\nprint("Hello from Studio Lite!")';S.nodes.push(n);S.selected=n.id;render();save(false);toast(type+" criado");if(type==="Script")openScript(n.id)}
function duplicate(){const n=cur();if(!n)return;commit();const d=clone(n);d.id=uid();d.name=n.name+" Copy";d.position=[...n.position];d.position[0]+=S.snap?S.grid*2:2;d.position[2]+=S.snap?S.grid*2:2;S.nodes.push(d);S.selected=d.id;render();toast("Objeto duplicado")}
function remove(){const n=cur();if(!n)return;if(n.id==="spawn")return toast("O SpawnLocation principal está protegido");commit();const ids=new Set([n.id]);let again=true;while(again){again=false;S.nodes.forEach(x=>{if(x.parent&&ids.has(x.parent)&&!ids.has(x.id)){ids.add(x.id);again=true}})}S.nodes=S.nodes.filter(x=>!ids.has(x.id));S.selected=S.nodes.find(x=>x.type==="Part")?.id||S.nodes[0]?.id||null;render();save(false);toast("Objeto excluído")}
function rename(){const n=cur();if(!n)return;openPrompt("Renomear objeto","Novo nome",n.name,v=>{if(v){commit();n.name=v;render();save(false)}})}
function setTool(t){S.tool=t;$$(".tool").forEach(x=>x.classList.toggle("active",x.dataset.tool===t));status({select:"Seleção",move:"Mover",rotate:"Rotacionar",scale:"Escalar"}[t]||t)}
function init(){try{scene=new THREE.Scene();scene.background=new THREE.Color("#030303");camera=new THREE.PerspectiveCamera(55,1,.05,1500);renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;$("#canvas").appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x111111,1.8));const l=new THREE.DirectionalLight(0xffffff,1.8);l.position.set(12,25,15);scene.add(l);editorGrid=new THREE.GridHelper(100,100,0x2c2c2c,0x111111);scene.add(editorGrid);target=new THREE.Vector3(0,1,0);ray=new THREE.Raycaster();pointer=new THREE.Vector2();selectionBox=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1,1,1)),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.9}));scene.add(selectionBox);selectionBox.visible=false;resize();renderer.domElement.oncontextmenu=e=>e.preventDefault();renderer.domElement.addEventListener("pointerdown",down);renderer.domElement.addEventListener("pointermove",move);renderer.domElement.addEventListener("pointerup",up);renderer.domElement.addEventListener("pointercancel",up);renderer.domElement.addEventListener("wheel",wheel,{passive:false});addEventListener("resize",resize);loop()}catch(err){console.error(err);status("WebGL indisponível");$("#canvas").innerHTML='<div class="empty" style="position:absolute;inset:0;display:grid;place-items:center">WebGL não pôde ser iniciado neste dispositivo.</div>'}}
function resize(){const e=$("#canvas");if(!e.clientWidth||!e.clientHeight)return;camera.aspect=e.clientWidth/e.clientHeight;camera.updateProjectionMatrix();renderer.setSize(e.clientWidth,e.clientHeight,false)}
function sync(){camera.position.set(target.x+radius*Math.sin(phi)*Math.sin(theta),target.y+radius*Math.cos(phi),target.z+radius*Math.sin(phi)*Math.cos(theta));camera.lookAt(target)}
function down(e){if(S.playing)return;if(e.button===1||e.button===2||e.shiftKey){orbit=true;lx=e.clientX;ly=e.clientY;return}const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects([...meshes.values()]).filter(h=>h.object.visible);if(hits[0]?.object.userData.id){const n=S.nodes.find(x=>x.id===hits[0].object.userData.id);if(n?.locked)return toast("Objeto bloqueado");S.selected=hits[0].object.userData.id;drag=S.tool!=="select";lx=e.clientX;ly=e.clientY;dragStart=clone(n);render();status("Selecionado")}else{S.selected=null;render()}}
function move(e){if(orbit){theta-=(e.clientX-lx)*.008;phi=Math.max(.1,Math.min(Math.PI-.1,phi-(e.clientY-ly)*.008));lx=e.clientX;ly=e.clientY;sync();return}if(!drag||!cur())return;const n=cur(),dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;if(!n._dragged){commit();n._dragged=true}
 if(S.tool==="move"){n.position[0]+=dx*.025;n.position[1]-=dy*.025;if(S.snap)n.position=n.position.map(v=>Math.round(v/S.grid)*S.grid)}
 if(S.tool==="rotate"){n.rotation[1]+=dx*.5;n.rotation[0]-=dy*.15;if(S.snap)n.rotation=n.rotation.map(v=>Math.round(v/15)*15)}
 if(S.tool==="scale"){const q=Math.max(.1,1-dy*.01);n.size=n.size.map(v=>Math.max(.1,v*q));if(S.snap)n.size=n.size.map(v=>Math.max(.1,Math.round(v/S.grid)*S.grid))}
 render(false)}
function up(){orbit=false;drag=false;S.nodes.forEach(n=>delete n._dragged);if(dragStart)save(false);dragStart=null}
function wheel(e){e.preventDefault();radius=Math.max(2,Math.min(160,radius*(e.deltaY>0?1.08:.92)));sync()}
function simulate(dt){if(!S.playing)return;dt=Math.min(Math.max(dt,0),.05);const physical=S.nodes.filter(n=>n.type!=="Folder"&&n.type!=="Script"&&n.visible!==false);for(const n of physical){if(n.anchored||!n.canCollide)continue;let v=simVelocity.get(n.id)||0;v-=28*dt;n.position[1]+=v*dt;const half=Math.max(.05,n.size[1]/2);let support=-Infinity;for(const floor of physical){if(floor.id===n.id||!floor.anchored||!floor.canCollide||floor.visible===false)continue;const ox=Math.abs(n.position[0]-floor.position[0]) <= (n.size[0]+floor.size[0])/2;const oz=Math.abs(n.position[2]-floor.position[2]) <= (n.size[2]+floor.size[2])/2;if(ox&&oz){const top=floor.position[1]+floor.size[1]/2;if(n.position[1]-half<=top+.15&&top>support)support=top}}if(support>-Infinity&&n.position[1]-half<support){n.position[1]=support+half;v=0}else if(n.position[1]-half<-.5){n.position[1]=-.5+half;v=0}simVelocity.set(n.id,v)}render(false)}
function copySelected(){const n=cur();if(!n)return toast("Selecione um objeto primeiro");S.clipboard=clone(n);toast("Objeto copiado")}
function pasteSelected(){if(!S.clipboard)return toast("Nenhum objeto copiado");commit();const n=clone(S.clipboard);n.id=uid();n.name=(n.name||"Object")+" Copy";n.position=[...(n.position||[0,2,0])];n.position[0]+=S.grid*2;n.position[2]+=S.grid*2;S.nodes.push(normalizeNode(n));S.selected=n.id;render();save(false);toast("Objeto colado")}
function newProject(){if(!confirm("Criar um projeto novo? Alterações não salvas serão substituídas."))return;commit();S.nodes=clone(initial);S.selected="base";S.project="Meu Primeiro Jogo";S.sourceRbxl=null;S.playSnapshot=null;simVelocity.clear();$("#projectName").value=S.project;view("home");render();save(false);toast("Novo projeto criado")}
function screenshot(){try{renderer.render(scene,camera);const a=document.createElement("a");a.download=(S.project||"studio-lite").replace(/[^a-z0-9_-]+/gi,"-")+".png";a.href=renderer.domElement.toDataURL("image/png");document.body.appendChild(a);a.click();a.remove();toast("Screenshot exportado")}catch(err){console.error(err);toast("Não foi possível capturar a viewport")}}
function loop(now=performance.now()){if(S.playing){const dt=(now-(simLast||now))/1000;simLast=now;simulate(dt)}renderer.render(scene,camera);requestAnimationFrame(loop)}
function meshFor(n){let m=meshes.get(n.id);if(!m){m=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({roughness:.65,metalness:.08,transparent:true}));m.userData.id=n.id;m.userData.shape="box";scene.add(m);meshes.set(n.id,m)}return m}
function geometryFor(n){const s=n.shape||"box";if(s==="sphere")return new THREE.SphereGeometry(.5,32,20);if(s==="cylinder")return new THREE.CylinderGeometry(.5,.5,1,32);if(s==="wedge"){const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(new Float32Array([-.5,-.5,-.5,.5,-.5,-.5,-.5,.5,-.5,-.5,-.5,.5,.5,-.5,.5,-.5,.5,.5]),3));g.setIndex([0,1,2,3,5,4,0,3,4,0,4,1,2,1,4,2,4,5,0,2,5,0,5,3]);g.computeVertexNormals();return g}return new THREE.BoxGeometry(1,1,1)}
function updateMeshes(){const ids=new Set();S.nodes.forEach(n=>{ids.add(n.id);const m=meshFor(n),shape=n.shape||"box";if(m.userData.shape!==shape){m.geometry.dispose();m.geometry=geometryFor(n);m.userData.shape=shape}m.position.set(...n.position);m.rotation.set(...n.rotation.map(v=>v*Math.PI/180));m.scale.set(...n.size);m.visible=!["Folder","Script"].includes(n.type)&&n.visible!==false;m.material.color.set(n.color||"#777");m.material.transparent=(n.transparency||0)>0;m.material.opacity=Math.max(.05,1-(n.transparency||0));m.material.roughness=n.material==="Glass"?.12:n.material==="Metal"?.3:.7;m.material.metalness=n.material==="Metal"?.8:n.material==="Neon"?.2:.05;m.material.emissive.set(n.material==="Neon"?(n.color||"#fff"):"#000");m.material.emissiveIntensity=n.material==="Neon"?.55:0});for(const [id,m] of meshes)if(!ids.has(id)){scene.remove(m);m.geometry.dispose();m.material.dispose();meshes.delete(id)}const n=cur();if(n&&S.settings.outline&&!["Folder","Script"].includes(n.type)&&n.visible!==false){selectionBox.visible=true;selectionBox.position.set(...n.position);selectionBox.rotation.set(...n.rotation.map(v=>v*Math.PI/180));selectionBox.scale.set(...n.size.map(v=>v*1.05))}else selectionBox.visible=false}
function tree(){const t=$("#tree"),filter=($("#treeSearch").value||"").toLowerCase();t.innerHTML='<div class="root">⌄ <b>Workspace</b></div>';const list=S.nodes.filter(n=>!filter||n.name.toLowerCase().includes(filter)||n.type.toLowerCase().includes(filter));list.forEach(n=>{const b=document.createElement("button");b.className="tree-row"+(n.id===S.selected?" selected":"");b.style.paddingLeft=(7+(n.parent?18:0))+"px";b.innerHTML="<span>"+icon(n)+"</span><span>"+esc(n.name)+"</span><span class=type>"+esc(n.type)+(n.locked?" 🔒":"")+"</span>";b.onclick=()=>{S.selected=n.id;render()};b.ondblclick=()=>rename();t.appendChild(b)});["Lighting","ReplicatedStorage","ServerScriptService","StarterGui","StarterPlayer"].forEach(x=>{const d=document.createElement("div");d.className="root muted";d.textContent="› "+x;t.appendChild(d)});$("#objectCount").textContent=S.nodes.length+" objetos"}
function panel(){const p=$("#panel");$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.panel===S.panel));if(S.panel==="toolbox"){p.innerHTML='<div class=panel-inner><input id=assetSearch class=search placeholder="⌕ Pesquisar objetos"><div class=section-title>STUDIO OBJECTS</div></div>';const root=p.firstChild;[["Part","Bloco físico"],["SpawnLocation","Ponto de spawn"],["Folder","Organizador"],["Script","Script Luau"]].forEach(([x,d])=>{const b=document.createElement("button");b.className="asset";b.dataset.asset=x;b.innerHTML='<span class=asset-icon>'+({Part:"◈",SpawnLocation:"⌂",Folder:"▱",Script:"◇"}[x])+'</span><span><b>'+x+'</b><small>'+d+'</small></span><strong>＋</strong>';b.onclick=()=>add(x);root.appendChild(b)});$("#assetSearch").oninput=e=>$$(".asset").forEach(a=>a.style.display=(!e.target.value||a.dataset.asset.toLowerCase().includes(e.target.value.toLowerCase()))?"flex":"none");return}
 const n=cur();if(!n){p.innerHTML='<div class=panel><div class=empty>Selecione um objeto no Explorer ou na cena.</div></div>';return}
 p.innerHTML='<div class=panel><div class=object><div class=object-icon>'+icon(n)+'</div><div><b>'+esc(n.name)+'</b><small>'+esc(n.type)+'</small></div></div></div>';const root=p.firstChild;
 section(root,"GENERAL");fieldText(root,"Name",n.name,v=>{if(v){commit();n.name=v;render();save(false)}});fieldText(root,"Class",n.type,()=>{},true);
 if(n.type!=="Folder"&&n.type!=="Script"){section(root,"TRANSFORM");vector(root,"Position",n.position,v=>{commit();n.position=v;render(false);save(false)});vector(root,"Rotation",n.rotation,v=>{commit();n.rotation=v;render(false);save(false)});vector(root,"Size",n.size,v=>{commit();n.size=v.map(x=>Math.max(.1,x));render(false);save(false)});
 section(root,"APPEARANCE");colorField(root,n);fieldSelect(root,"Material",n.material||"Plastic",v=>{commit();n.material=v;render(false);save(false)});fieldNumber(root,"Transparency",n.transparency||0,.05,0,1,v=>{commit();n.transparency=v;render(false);save(false)});
 section(root,"BEHAVIOR");toggle(root,"Anchored",n.anchored,v=>{commit();n.anchored=v;save(false)});toggle(root,"CanCollide",n.canCollide,v=>{commit();n.canCollide=v;save(false)});toggle(root,"Locked",n.locked,v=>{commit();n.locked=v;save(false)});toggle(root,"Visible",n.visible!==false,v=>{commit();n.visible=v;render(false);save(false)});
 section(root,"ACTIONS");const row=document.createElement("div");row.className="modal-actions";const db=document.createElement("button");db.textContent="Duplicate";db.onclick=duplicate;const xb=document.createElement("button");xb.textContent="Delete";xb.className="danger";xb.onclick=remove;row.append(db,xb);root.appendChild(row)}
 if(n.type==="Script"){section(root,"SCRIPT");const b=document.createElement("button");b.className="wide primary";b.textContent="Abrir Script Editor";b.onclick=()=>openScript(n.id);root.appendChild(b)}
}
function section(p,t){const d=document.createElement("div");d.className="section-title";d.textContent=t;p.appendChild(d)}
function fieldText(p,t,v,fn,disabled=false){const d=document.createElement("div");d.className="field";d.innerHTML="<span>"+t+"</span><input "+(disabled?"disabled ":"")+"value=\""+esc(v)+"\">";const i=d.querySelector("input");if(!disabled)i.onchange=()=>fn(i.value.trim());p.appendChild(d)}
function fieldNumber(p,t,v,step,min,max,fn){const d=document.createElement("div");d.className="field";d.innerHTML="<span>"+t+"</span><input type=number step="+step+" min="+min+" max="+max+" value="+v+">";d.querySelector("input").onchange=e=>fn(Math.max(min,Math.min(max,Number(e.target.value)||0)));p.appendChild(d)}
function fieldSelect(p,t,v,fn){const d=document.createElement("div");d.className="field";d.innerHTML="<span>"+t+"</span><select><option>Plastic</option><option>Metal</option><option>Wood</option><option>Glass</option><option>Neon</option></select>";const s=d.querySelector("select");s.value=v;s.onchange=()=>fn(s.value);p.appendChild(d)}
function colorField(p,n){const d=document.createElement("div");d.className="field";d.innerHTML="<span>Color</span><input type=color value=\""+(n.color||"#777")+"\">";const i=d.querySelector("input");i.oninput=e=>{n.color=e.target.value;updateMeshes()};i.onchange=()=>{commit();save(false)};p.appendChild(d)}
function vector(p,t,a,fn){const d=document.createElement("div");d.className="vector";d.innerHTML="<span>"+t+"</span><div></div>";a.forEach((v,i)=>{const x=document.createElement("input");x.type="number";x.step="0.1";x.value=Number(v.toFixed(3));x.onchange=()=>{const b=[...a];b[i]=Number(x.value)||0;fn(b);panel()};d.lastChild.appendChild(x)});p.appendChild(d)}
function toggle(p,t,v,fn){const d=document.createElement("div");d.className="toggle";d.innerHTML="<span>"+t+"</span><button class=switch "+(v?"on":"")+" aria-label="+t+"><i></i></button>";d.lastChild.onclick=()=>{fn(!v);panel()};p.appendChild(d)}
function render(full=true){if(full){tree();panel()}updateMeshes();const n=cur();$("#selectionInfo").textContent=n?(n.name+" • "+n.type):"Nenhum objeto selecionado";$("#gridHud").textContent="Grid "+S.grid+" stud"+(S.grid===1?"":"s")}
function focus(){const n=cur();if(!n)return;target.set(...n.position);radius=Math.max(7,Math.max(...n.size)*3);sync();toast("Câmera focada")}
function view(kind){if(kind==="home"){theta=.62;phi=.92;radius=27;target.set(0,1,0)}if(kind==="top"){theta=0;phi=.08;radius=28}if(kind==="front"){theta=0;phi=1.57;radius=28}if(kind==="right"){theta=1.57;phi=1.57;radius=28}sync()}
function toggleGrid(){if(editorGrid){editorGrid.visible=!editorGrid.visible;toast(editorGrid.visible?"Grid visível":"Grid oculto")}}
function panCamera(dx,dy){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1),amount=radius*.0025;target.addScaledVector(right,dx*amount);target.addScaledVector(up,dy*amount);sync()}
function commandPalette(){const bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=modal><div class=modal-head><h2>Command Palette</h2><button id=cpX>×</button></div><input id=cpSearch placeholder="Pesquisar comando…"><div id=cpList></div></div>';$("#modalRoot").appendChild(bg);const cs=[["Criar Part",()=>add("Part")],["Criar Sphere",()=>add("Sphere")],["Criar Cylinder",()=>add("Cylinder")],["Criar Wedge",()=>add("Wedge")],["Duplicar",duplicate],["Excluir",remove],["Focar",focus],["Grid",toggleGrid],["Salvar",save],["Desfazer",undo],["Refazer",redo],["Exportar",exportProject],["Publicar",publish]];const draw=()=>{const q=$("#cpSearch").value.toLowerCase(),l=$("#cpList");l.innerHTML="";cs.filter(x=>x[0].toLowerCase().includes(q)).forEach(x=>{const b=document.createElement("button");b.className="asset";b.textContent=x[0];b.onclick=()=>{bg.remove();x[1]()};l.appendChild(b)})};$("#cpSearch").oninput=draw;$("#cpX").onclick=()=>bg.remove();draw();setTimeout(()=>$("#cpSearch").focus(),20)}
function openScript(id){const n=S.nodes.find(x=>x.id===id);if(!n)return;const bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=script-window><div class=script-head><b>◇ '+esc(n.name)+'</b><div><button id=ss class=primary>Salvar</button> <button id=sc>×</button></div></div><div class=editor><div class=lines id=lines></div><textarea class=script-area id=st spellcheck=false></textarea></div><div class=script-foot>Luau • UTF-8 • <span id=lc>0</span> linhas</div></div>';$("#modalRoot").appendChild(bg);const ta=$("#st"),ln=$("#lines");ta.value=n.script||"-- Novo Script\n";const syncLines=()=>{ln.innerHTML=ta.value.split("\n").map((_,i)=>i+1).join("<br>");$("#lc").textContent=ta.value.split("\n").length};syncLines();ta.oninput=syncLines;$("#sc").onclick=()=>bg.remove();$("#ss").onclick=()=>{commit();n.script=ta.value;bg.remove();save();toast("Script salvo")};ta.addEventListener("keydown",e=>{if(e.key==="Tab"){e.preventDefault();const a=ta.selectionStart,b=ta.selectionEnd;ta.value=ta.value.slice(0,a)+"    "+ta.value.slice(b);ta.selectionStart=ta.selectionEnd=a+4;syncLines()}});
}
function openPrompt(title,label,value,fn){const bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=modal><div class=modal-head><h2>'+esc(title)+'</h2><button id=x>×</button></div><p>'+esc(label)+'</p><input id=v value="'+esc(value)+'"><div class=modal-actions><button id=c>Cancelar</button><button id=o class=primary>Confirmar</button></div></div>';$("#modalRoot").appendChild(bg);$("#x").onclick=$("#c").onclick=()=>bg.remove();$("#o").onclick=()=>{const v=$("#v").value.trim();bg.remove();fn(v)};setTimeout(()=>$("#v").focus(),20)}
function publish(){
 const bg=document.createElement("div");bg.className="modal-bg";
 bg.innerHTML='<div class=modal><div class=modal-head><div><h2>Publicar no Roblox</h2><small style="color:#555">Open Cloud • Place Publishing</small></div><button id=x>×</button></div><p>Envie um arquivo <b>.rbxl</b> ou <b>.rbxlx</b> diretamente para o Place atual. A API Key é usada somente nesta sessão e <b>não é salva no localStorage</b>.</p><div class=notice><strong>Importante:</strong> para publicar um arquivo editado pelo Studio Lite, o arquivo precisa ser um .rbxl válido. O editor preserva um .rbxl importado para publicação; o exportador web gera RBXLX/JSON.</div><h3>CREDENCIAIS DO JOGO</h3><div class=row><input id=universe placeholder="Universe ID"><input id=place placeholder="Place ID"></div><input id=api type=password placeholder="Roblox Open Cloud API Key" autocomplete="off"><h3>ARQUIVO DO PLACE</h3><input id=pubfile type=file accept=".rbxl,.rbxlx"><label class=checkline><input id=useEditorFile type=checkbox> publicar o RBXLX gerado pelo editor</label><label class=checkline><input id=rememberIds type=checkbox> lembrar apenas Universe/Place ID neste dispositivo</label><div class=notice>Permissão necessária: a chave deve ter acesso de publicação do Place. O navegador pode bloquear a chamada direta por CORS; nesse caso use um endpoint PHP seguro.</div><div class=modal-actions><button id=c>Cancelar</button><button id=publishNow class=primary>↑ Enviar e Publicar</button></div><div id=pubstatus style="color:#666;font-size:11px;margin-top:8px"></div></div>';
 $("#modalRoot").appendChild(bg);
 try{const ids=JSON.parse(localStorage.getItem("studio-roblox-target")||"{}");$("#universe").value=ids.universe||"";$("#place").value=ids.place||""}catch{} $("#pubfile").onchange=()=>{const f=$("#pubfile").files[0];if(f)$("#pubstatus").textContent="Arquivo selecionado: "+f.name+" ("+Math.ceil(f.size/1024/1024*100)/100+" MB)"};
 $("#x").onclick=$("#c").onclick=()=>bg.remove();
 $("#publishNow").onclick=async()=>{const universe=$("#universe").value.trim(),place=$("#place").value.trim(),api=$("#api").value.trim();let file=$("#pubfile").files[0]||S.sourceRbxl;if($("#useEditorFile").checked)file=new File([exportXML()],(S.project||"studio-project")+".rbxlx",{type:"application/xml"});
   if(!/^\d+$/.test(universe)||!/^\d+$/.test(place))return toast("Universe ID e Place ID devem ser numéricos");
   if(!api)return toast("Informe a API Key da Roblox");if(!file)return toast("Selecione um .rbxl/.rbxlx ou marque para publicar o RBXLX do editor");if(!/\.rbxlx?$/i.test(file.name))return toast("O arquivo precisa terminar em .rbxl ou .rbxlx");
   if($("#rememberIds").checked)localStorage.setItem("studio-roblox-target",JSON.stringify({universe,place}));
   $("#pubstatus").textContent="Enviando arquivo para Roblox…";$("#publishNow").disabled=true;status("Publicando…");
   try{const url="https://apis.roblox.com/universes/v1/"+encodeURIComponent(universe)+"/places/"+encodeURIComponent(place)+"/versions?versionType=Published";const res=await fetch(url,{method:"POST",headers:{"x-api-key":api,"Content-Type":file.name.toLowerCase().endsWith(".rbxlx")?"application/xml":"application/octet-stream"},body:await file.arrayBuffer()});const textBody=await res.text();if(!res.ok)throw Error("HTTP "+res.status+" — "+textBody.slice(0,240));$("#pubstatus").textContent="Publicado com sucesso.";status("Publicado");toast("Place publicado no Roblox");setTimeout(()=>bg.remove(),1100)}catch(err){console.error(err);$("#pubstatus").textContent="Falha: "+err.message;status("Falha na publicação");$("#publishNow").disabled=false;toast("Não foi possível publicar diretamente")}}
}
function exportXML(){const xe=s=>String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;");const parts=S.nodes.filter(n=>["Part","SpawnLocation"].includes(n.type));const items=parts.map(n=>"<Item class=\""+n.type+"\" referent=\"RBX"+n.id+"\"><Properties><string name=\"Name\">"+xe(n.name)+"</string><bool name=\"Anchored\">"+!!n.anchored+"</bool><bool name=\"CanCollide\">"+!!n.canCollide+"</bool><Vector3 name=\"size\"><X>"+n.size[0]+"</X><Y>"+n.size[1]+"</Y><Z>"+n.size[2]+"</Z></Vector3><CoordinateFrame name=\"CFrame\"><X>"+n.position[0]+"</X><Y>"+n.position[1]+"</Y><Z>"+n.position[2]+"</Z><R00>1</R00><R01>0</R01><R02>0</R02><R10>0</R10><R11>1</R11><R12>0</R12><R20>0</R20><R21>0</R21><R22>1</R22></CoordinateFrame></Properties></Item>").join("");return"<?xml version=\"1.0\" encoding=\"utf-8\"?><roblox version=\"4\"><Item class=\"Workspace\" referent=\"RBXWorkspace\"><Properties><string name=\"Name\">Workspace</string></Properties>"+items+"</Item></roblox>"}
function download(name,data,type){const b=new Blob([data],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function exportProject(){const bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=modal><div class=modal-head><h2>Exportar projeto</h2><button id=x>×</button></div><p>Escolha o formato. JSON preserva todos os dados do editor; RBXLX cria um DataModel XML simplificado.</p><div class=modal-actions><button id=json>JSON completo</button><button id=rbxlx class=primary>RBXLX</button></div></div>';$("#modalRoot").appendChild(bg);$("#x").onclick=()=>bg.remove();$("#json").onclick=()=>{download((S.project||"studio-project")+".json",JSON.stringify({name:S.project,nodes:S.nodes},null,2),"application/json");bg.remove();toast("JSON exportado")};$("#rbxlx").onclick=()=>{download((S.project||"studio-project")+".rbxlx",exportXML(),"application/xml");bg.remove();toast("RBXLX exportado")}}
async function importFile(f){if(!f)return;status("Importando…");const name=f.name.toLowerCase();try{
 if(name.endsWith(".rbxl")){S.sourceRbxl=f;status("RBXL pronto para publicação");toast("RBXL carregado — agora use Publicar para enviar ao jogo");return}
 if(name.endsWith(".json")){const d=JSON.parse(await f.text());if(!Array.isArray(d.nodes))throw Error();commit();S.nodes=d.nodes.map(normalizeNode);S.project=d.name||S.project;$("#projectName").value=S.project;S.selected=S.nodes[0]?.id||null;render();save(false);toast("Projeto JSON importado");return}
 const doc=new DOMParser().parseFromString(await f.text(),"application/xml");if(doc.querySelector("parsererror"))throw Error();const els=[...doc.querySelectorAll("Item")].filter(e=>["Part","SpawnLocation","WedgePart","CornerWedgePart","MeshPart"].includes(e.getAttribute("class")));const out=els.map((e,i)=>{const prop=n=>e.querySelector('Properties > *[name="'+n+'"]'),txt=n=>prop(n)?.textContent||"";const vec=n=>{const z=prop(n);if(!z)return[0,0,0];return[+z.querySelector("X")?.textContent||0,+z.querySelector("Y")?.textContent||0,+z.querySelector("Z")?.textContent||0]};return normalizeNode({id:uid(),name:txt("Name")||"Part "+(i+1),type:e.getAttribute("class")==="MeshPart"?"Part":e.getAttribute("class"),position:vec("CFrame"),rotation:[0,0,0],size:vec("size").map(v=>v||1),color:"#64748b",material:"Plastic",anchored:txt("Anchored")==="true",canCollide:txt("CanCollide")!=="false",parent:null})});if(!out.length)return toast("Nenhum objeto compatível encontrado");commit();S.nodes=out;S.selected=out[0].id;S.sourceRbxl=null;render();save(false);toast(out.length+" objetos importados")
}catch(e){console.error(e);status("Falha na importação");toast("Arquivo inválido ou incompatível")}}
function normalizeNode(n){const d=Object.assign({id:uid(),name:"Object",type:"Part",position:[0,0,0],rotation:[0,0,0],size:[1,1,1],color:"#777",material:"Plastic",shape:"box",anchored:true,canCollide:true,transparency:0,locked:false,visible:true,parent:null},n||{});d.id=d.id||uid();d.name=String(d.name||"Object").slice(0,100);d.type=["Part","SpawnLocation","Folder","Script","Sphere","Cylinder","Wedge"].includes(d.type)?d.type:"Part";["position","rotation","size"].forEach(k=>{d[k]=Array.isArray(d[k])?d[k].slice(0,3).map(v=>Number(v)||0):[0,0,0]});d.size=d.size.map(v=>Math.max(.1,Math.abs(Number(v)||1)));d.transparency=Math.max(0,Math.min(1,Number(d.transparency)||0));d.visible=d.visible!==false;d.anchored=d.anchored!==false;d.canCollide=d.canCollide!==false;d.locked=!!d.locked;d.shape=d.shape||({Sphere:"sphere",Cylinder:"cylinder",Wedge:"wedge"}[d.type]||"box");return d}
function play(){if(!S.playing){S.playSnapshot={nodes:clone(S.nodes),selected:S.selected,project:S.project};simVelocity.clear();simLast=performance.now();S.playing=true}else{S.playing=false;if(S.playSnapshot){S.nodes=clone(S.playSnapshot.nodes);S.selected=S.playSnapshot.selected;S.project=S.playSnapshot.project;$("#projectName").value=S.project}S.playSnapshot=null;simVelocity.clear();render()}$("#playBadge").classList.toggle("on",S.playing);$("#playBtn").textContent=S.playing?"■ Stop":"▶ Play";status(S.playing?"Play Mode iniciado":"Edição retomada");toast(S.playing?"Play Mode":"Edição retomada")}
function settings(){
 const bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=modal><div class=modal-head><h2>Configurações</h2><button id=x>×</button></div><h3>EDITOR</h3><label class=checkline><input id=outline type=checkbox '+(S.settings.outline?"checked":"")+'> mostrar contorno de seleção</label><label class=checkline><input id=autosave type=checkbox checked> autosave local</label>><h3>ATALHOS</h3><div class=notice><b>W</b> mover · <b>E</b> girar · <b>R</b> escala · <b>F</b> focar · <b>Ctrl/⌘ D</b> duplicar · <b>Ctrl/⌘ Z</b> desfazer · <b>Ctrl/⌘ S</b> salvar · <b>P</b> publicar · <b>ESC</b> fechar modo Play</div><h3>DADOS</h3><div class=modal-actions><button id=clear class=danger>Limpar projeto local</button><button id=close class=primary>Concluir</button></div></div>';$("#modalRoot").appendChild(bg);$("#x").onclick=$("#close").onclick=()=>{S.settings.outline=$("#outline").checked;S.settings.autosave=$("#autosave").checked;save(false);bg.remove();render(false)};$("#clear").onclick=()=>{if(confirm("Apagar o projeto salvo neste dispositivo?")){localStorage.removeItem("studio-lite-v4");localStorage.removeItem("studio-roblox-target");location.reload()}}}
function togglePanels(which){$("#explorerPanel").classList.toggle("open",which==="explorer");$("#inspectorPanel").classList.toggle("open",which==="inspector")}
$("#saveBtn").onclick=()=>save();$("#newBtn").onclick=newProject;$("#screenshotBtn").onclick=screenshot;$("#undoBtn").onclick=undo;$("#redoBtn").onclick=redo;$("#duplicateBtn").onclick=duplicate;$("#deleteBtn").onclick=remove;$("#renameBtn").onclick=rename;$("#focusBtn").onclick=focus;$("#publishBtn").onclick=publish;$("#publishRbxlBtn").onclick=()=>publish();$("#settingsBtn").onclick=settings;$("#exportBtn").onclick=exportProject;$("#importBtn").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>{importFile(e.target.files[0]);e.target.value=""};$("#projectName").onchange=e=>{commit();S.project=e.target.value.trim()||"Meu Primeiro Jogo";save(false)};$("#playBtn").onclick=play;$("#gridBtn").onclick=()=>{S.grid=S.grid===1 ? .5 : S.grid===.5 ? .25 : S.grid===.25 ? .1 : 1;render();toast("Grid "+S.grid)};$("#snapBtn").onclick=()=>{S.snap=!S.snap;$("#snapBtn").textContent="Snap: "+(S.snap?"ON":"OFF");toast("Snap "+(S.snap?"ativado":"desativado"))};$("#treeSearch").oninput=tree;$("#homeView").onclick=()=>view("home");$("#topView").onclick=()=>view("top");$("#frontView").onclick=()=>view("front");$("#rightView").onclick=()=>view("right");$("#fullscreenBtn").onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.();};$("#explorerToggle").onclick=()=>togglePanels("explorer");$("#inspectorToggle").onclick=()=>togglePanels("inspector");$("#collapseBtn").onclick=()=>togglePanels("explorer");
$("#gridToggleBtn").onclick=toggleGrid;$("#commandBtn").onclick=commandPalette;$("#gridBtn").ondblclick=toggleGrid;document.addEventListener("click",e=>{const a=e.target.closest("[data-add]");if(a)add(a.dataset.add);const t=e.target.closest("[data-tool]");if(t)setTool(t.dataset.tool);const p=e.target.closest("[data-panel]");if(p){S.panel=p.dataset.panel;panel()}});
addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();save();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"){e.preventDefault();duplicate();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="c"){if(!/input|textarea|select/i.test(e.target.tagName)){e.preventDefault();copySelected()}return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="v"){if(!/input|textarea|select/i.test(e.target.tagName)){e.preventDefault();pasteSelected()}return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();commandPalette();return}if(/input|textarea|select/i.test(e.target.tagName))return;const k=e.key.toLowerCase();if(k==="delete"||k==="backspace")remove();if(k==="w")setTool("move");if(k==="e")setTool("rotate");if(k==="r")setTool("scale");if(k==="f")focus();if(k==="p")publish();if(k==="escape"&&S.playing)play();if(k==="arrowup")panCamera(0,-12);if(k==="arrowdown")panCamera(0,12);if(k==="arrowleft")panCamera(-12,0);if(k==="arrowright")panCamera(12,0)});
try{const d=JSON.parse(localStorage.getItem("studio-lite-v4"));if(d?.nodes){S.nodes=d.nodes.map(normalizeNode);S.project=d.name||S.project;S.settings=Object.assign(S.settings,d.settings||{});S.grid=[1,.5,.25,.1].includes(d.grid)?d.grid:1;S.snap=d.snap!==false;$("#projectName").value=S.project}}catch{}
init();if(renderer){sync();render();status("Pronto")}else{status("Modo 3D indisponível")}setInterval(()=>{if(!S.playing&&S.settings.autosave!==false)save(false)},30000);$("#deviceInfo").textContent="HTML • CSS • JS • THREE.JS • "+(innerWidth<=600?"MOBILE":"DESKTOP");

/* ===== STUDIO LITE PRO EXPANSION ===== */
S.selectedIds=S.selectedIds||[S.selected].filter(Boolean);
S.proVersion="5.0 PRO";
const _baseAdd=add,_baseRender=render,_basePanel=panel,_baseTree=tree,_baseSave=save,_baseDuplicate=duplicate,_baseRemove=remove;
function proSelect(id,multi=false){if(multi){if(S.selectedIds.includes(id))S.selectedIds=S.selectedIds.filter(x=>x!==id);else S.selectedIds.push(id)}else S.selectedIds=id?[id]:[];S.selected=S.selectedIds.at(-1)||null}
function proChildren(id){return S.nodes.filter(n=>(n.parent||null)===(id||null))}
function proDescendant(id,root){let n=S.nodes.find(x=>x.id===id),seen=new Set();while(n&&n.parent&&!seen.has(n.parent)){if(n.parent===root)return true;seen.add(n.parent);n=S.nodes.find(x=>x.id===n.parent)}return false}
function proGroup(){
 const ids=S.selectedIds.filter(id=>S.nodes.some(n=>n.id===id));if(!ids.length)return toast("Selecione pelo menos um objeto");
 commit();const m={id:uid(),name:"Model",type:"Model",position:[0,0,0],rotation:[0,0,0],size:[1,1,1],color:"#64748b",material:"Plastic",anchored:true,canCollide:false,transparency:0,locked:false,visible:true,parent:null};
 S.nodes.push(m);S.nodes.forEach(n=>{if(ids.includes(n.id))n.parent=m.id});proSelect(m.id);render();save(false);toast("Model criado")
}
function proUngroup(){const n=cur();if(!n||n.type!=="Model")return toast("Selecione um Model");commit();S.nodes.forEach(x=>{if(x.parent===n.id)x.parent=n.parent||null});S.nodes=S.nodes.filter(x=>x.id!==n.id);proSelect(null);render();save(false);toast("Model desagrupado")}
function proAdd(type){
 if(type==="Model"){commit();const n={id:uid(),name:"Model",type:"Model",position:[0,0,0],rotation:[0,0,0],size:[1,1,1],color:"#64748b",material:"Plastic",anchored:true,canCollide:false,transparency:0,locked:false,visible:true,parent:null};S.nodes.push(n);proSelect(n.id);render();save(false);return toast("Model criado")}
 _baseAdd(type==="MeshPart"||type==="Terrain"?"Part":type);
 const n=cur();if(!n)return;
 n.type=type;n.canCollide=!["Folder","Script","Model"].includes(type);n.parent=cur()&&S.selectedIds.length>1?null:n.parent;
 if(type==="MeshPart")n.meshId=n.meshId||"";if(type==="Terrain")n.terrain={brush:"block",resolution:4};
 if(type==="Terrain")n.material="Grass";
 render();save(false)
}
function proTree(){
 const t=$("#tree"),filter=($("#treeSearch").value||"").toLowerCase();t.innerHTML='<div class="root">⌄ <b>Workspace</b></div>';
 function walk(parent,depth){proChildren(parent).forEach(n=>{const match=!filter||n.name.toLowerCase().includes(filter)||n.type.toLowerCase().includes(filter);if(match){const b=document.createElement("button");b.className="tree-row"+(S.selectedIds.includes(n.id)?" selected":"");b.style.paddingLeft=(7+depth*18)+"px";const branch=proChildren(n.id).length?"▾":"•";b.innerHTML="<span>"+branch+" "+icon(n)+"</span><span>"+esc(n.name)+"</span><span class=type>"+esc(n.type)+(n.locked?" 🔒":"")+"</span>";b.onclick=e=>{proSelect(n.id,e.ctrlKey||e.metaKey||e.shiftKey);render()};b.ondblclick=()=>rename();t.appendChild(b)}walk(n.id,depth+1)})}
 walk(null,0);["Lighting","ReplicatedStorage","ServerScriptService","StarterGui","StarterPlayer"].forEach(x=>{const d=document.createElement("div");d.className="root muted";d.textContent="› "+x;t.appendChild(d)});
 $("#objectCount").textContent=S.nodes.length+" objetos"+(S.selectedIds.length?" • "+S.selectedIds.length+" selecionados":"")
}
function proPanel(){
 _basePanel();
 const p=$("#panel");if(S.panel==="toolbox"){const root=p.querySelector(".panel");if(root&&!root.dataset.pro){root.dataset.pro="1";[["Sphere","Esfera"],["Cylinder","Cilindro"],["Wedge","Cunha"],["Model","Modelo"],["MeshPart","MeshPart"],["Terrain","Terreno"]].forEach(([x,d])=>{const b=document.createElement("button");b.className="asset";b.innerHTML='<span class=asset-icon>◇</span><span><b>'+x+'</b><small>'+d+'</small></span><strong>＋</strong>';b.onclick=()=>proAdd(x);root.appendChild(b)});const tools=document.createElement("div");tools.innerHTML='<div class=section-title>WORKSPACE TOOLS</div><button class=wide id=proGroup>▣ Group Selected</button><button class=wide id=proUngroup>▱ Ungroup Model</button><button class=wide id=proValidate>✓ Validate Project</button>';root.appendChild(tools);$("#proGroup").onclick=proGroup;$("#proUngroup").onclick=proUngroup;$("#proValidate").onclick=validateProject}return}
 const n=cur();if(!n)return;
 const root=p.querySelector(".panel");if(!root||root.dataset.pro)return;root.dataset.pro="1";
 const sec=document.createElement("div");sec.innerHTML='<div class=section-title>HIERARCHY</div>';const sel=document.createElement("select");sel.style.cssText="width:100%;background:#0e0e0e;border:1px solid #252525;border-radius:5px;color:#ddd;padding:7px";sel.innerHTML='<option value="">Workspace</option>'+S.nodes.filter(x=>x.id!==n.id&&["Folder","Model"].includes(x.type)).map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join("");sel.value=n.parent||"";sel.onchange=()=>{const v=sel.value;if(v===n.id||proDescendant(v,n.id))return toast("Parent inválido");commit();n.parent=v||null;render();save(false)};sec.appendChild(sel);root.appendChild(sec);
 const adv=document.createElement("div");adv.innerHTML='<div class=section-title>ADVANCED</div>';const rows=[["Reflectance",n.reflectance||0,0,1,.05],["Surface",n.surface||"Smooth",null,null,null]];const ref=document.createElement("input");ref.type="number";ref.min=0;ref.max=1;ref.step=.05;ref.value=n.reflectance||0;ref.onchange=()=>{commit();n.reflectance=+ref.value||0;save(false)};adv.appendChild(labelWrap("Reflectance",ref));const surface=document.createElement("select");["Smooth","Studs","Inlet","Universal","Hinge","Motor"].forEach(x=>surface.add(new Option(x,x)));surface.value=n.surface||"Smooth";surface.onchange=()=>{commit();n.surface=surface.value;save(false)};adv.appendChild(labelWrap("Surface",surface));root.appendChild(adv);
 if(n.type==="MeshPart"){const a=document.createElement("div");a.innerHTML='<div class=section-title>MESH</div>';const inp=document.createElement("input");inp.className="search";inp.placeholder="rbxassetid://...";inp.value=n.meshId||"";inp.onchange=()=>{commit();n.meshId=inp.value;save(false)};a.appendChild(inp);root.appendChild(a)}
 if(n.type==="Terrain"){const a=document.createElement("div");a.innerHTML='<div class=section-title>TERRAIN BRUSH</div>';["block","sphere","smooth","paint"].forEach(x=>{const b=document.createElement("button");b.textContent=x;b.style.margin="3px";b.onclick=()=>{n.terrain=n.terrain||{};n.terrain.brush=x;save(false);toast("Brush: "+x)};a.appendChild(b)});root.appendChild(a)}
}
function labelWrap(name,input){const d=document.createElement("div");d.className="field";const s=document.createElement("span");s.textContent=name;d.append(s,input);return d}
function validateProject(){
 const issues=[],ids=new Set();S.nodes.forEach(n=>{if(ids.has(n.id))issues.push("ID duplicado: "+n.id);ids.add(n.id);if(!n.name)issues.push("Objeto sem nome");if(n.parent&&!S.nodes.some(x=>x.id===n.parent))issues.push("Parent inexistente: "+n.name);if(!Array.isArray(n.position)||n.position.length!==3)issues.push("Position inválida: "+n.name);if(!Array.isArray(n.size)||n.size.some(v=>v<=0))issues.push("Size inválido: "+n.name)});
 const bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=modal><div class=modal-head><h2>Project Validation</h2><button id=px>×</button></div><div class=notice><strong>'+(!issues.length?"✓ Projeto pronto para exportação":"⚠ "+issues.length+" problema(s)")+'</strong><br>'+(!issues.length?"Nenhum erro estrutural encontrado.":"<br>"+issues.map(esc).join("<br>"))+'</div><div class=modal-actions><button id=pc class=primary>Concluir</button></div></div>';$("#modalRoot").appendChild(bg);$("#px").onclick=$("#pc").onclick=()=>bg.remove();return issues
}
function proDuplicate(){const ids=S.selectedIds.slice();if(ids.length<2)return _baseDuplicate();commit();const map=new Map();const copies=ids.map(id=>{const n=S.nodes.find(x=>x.id===id);const x=clone(n);x.id=uid();x.name=n.name+" Copy";x.position=x.position.map((v,i)=>v+(i===0||i===2?S.grid*2:0));map.set(id,x.id);return x});copies.forEach(x=>{if(x.parent&&map.has(x.parent))x.parent=map.get(x.parent)});S.nodes.push(...copies);S.selectedIds=copies.map(x=>x.id);S.selected=S.selectedIds.at(-1);render();save(false);toast(copies.length+" objetos duplicados")}
function proRemove(){if(S.selectedIds.length<2)return _baseRemove();commit();const ids=new Set(S.selectedIds);S.nodes=S.nodes.filter(n=>!ids.has(n.id)&&!proDescendant(n.id,[...ids][0]));proSelect(null);render();save(false);toast("Objetos removidos")}
function proRender(full=true){S.selectedIds=S.selectedIds||[S.selected].filter(Boolean);_baseRender(full)}
add=proAdd;tree=proTree;panel=proPanel;duplicate=proDuplicate;remove=proRemove;render=proRender;
const _oldSave=save;save=function(show=true){S.selectedIds=S.selectedIds||[S.selected].filter(Boolean);return _oldSave(show)};
$("[data-add]").forEach(b=>b.onclick=()=>proAdd(b.dataset.add));
$("#validateBtn")&&($("#validateBtn").onclick=validateProject);


/* PRO INPUT + EXPORT */
const _proDownBase=down;
down=function(e){
 if(S.playing)return;
 if(e.button===1||e.button===2){orbit=true;lx=e.clientX;ly=e.clientY;return}
 const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);
 const hit=ray.intersectObjects([...meshes.values()]).find(h=>h.object.visible);
 if(!hit){if(!(e.ctrlKey||e.metaKey||e.shiftKey)){proSelect(null);render()}return}
 const id=hit.object.userData.id,n=S.nodes.find(x=>x.id===id);if(!n||n.locked)return toast("Objeto bloqueado");
 proSelect(id,e.ctrlKey||e.metaKey||e.shiftKey);drag=S.tool!=="select";lx=e.clientX;ly=e.clientY;dragStart=clone(n);render();status(S.selectedIds.length>1?S.selectedIds.length+" selecionados":"Selecionado")
};
const _proMoveBase=move;
move=function(e){
 if(orbit){theta-=(e.clientX-lx)*.008;phi=Math.max(.1,Math.min(Math.PI-.1,phi-(e.clientY-ly)*.008));lx=e.clientX;ly=e.clientY;sync();return}
 if(!drag||!cur())return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;const ns=S.nodes.filter(n=>S.selectedIds.includes(n.id)&&!n.locked);if(!ns.length)return;if(!ns.some(n=>n._dragged)){commit();ns.forEach(n=>n._dragged=true)}
 ns.forEach(n=>{if(S.tool==="move"){n.position[0]+=dx*.025;n.position[1]-=dy*.025;if(S.snap)n.position=n.position.map(v=>Math.round(v/S.grid)*S.grid)}else if(S.tool==="rotate"){n.rotation[1]+=dx*.5;n.rotation[0]-=dy*.15;if(S.snap)n.rotation=n.rotation.map(v=>Math.round(v/15)*15)}else if(S.tool==="scale"){const q=Math.max(.1,1-dy*.01);n.size=n.size.map(v=>Math.max(.1,v*q));if(S.snap)n.size=n.size.map(v=>Math.max(.1,Math.round(v/S.grid)*S.grid))}});render(false)
};
function proExportXML(){
 const escx=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");
 const vec=(name,a)=>'<Vector3 name="'+name+'"><X>'+a[0]+'</X><Y>'+a[1]+'</Y><Z>'+a[2]+'</Z></Vector3>';
 function item(n){let body='<string name="Name">'+escx(n.name)+'</string>';if(n.type!=="Folder"&&n.type!=="Model"&&n.type!=="Script"){body+='<bool name="Anchored">'+!!n.anchored+'</bool><bool name="CanCollide">'+!!n.canCollide+'</bool>'+vec("size",n.size)+'<CoordinateFrame name="CFrame"><X>'+n.position[0]+'</X><Y>'+n.position[1]+'</Y><Z>'+n.position[2]+'</Z><R00>1</R00><R01>0</R01><R02>0</R02><R10>0</R10><R11>1</R11><R12>0</R12><R20>0</R20><R21>0</R21><R22>1</R22></CoordinateFrame>'}if(n.type==="Script")body+='<ProtectedString name="Source">'+escx(n.script||"")+'</ProtectedString>';let kids=S.nodes.filter(x=>x.parent===n.id).map(item).join("");const cls=n.type==="Sphere"||n.type==="Cylinder"||n.type==="Wedge"?"Part":n.type==="Model"?"Model":n.type;return '<Item class="'+cls+'" referent="RBX'+escx(n.id)+'"><Properties>'+body+'</Properties>'+kids+'</Item>'}
 const roots=S.nodes.filter(n=>!n.parent).map(item).join("");return '<?xml version="1.0" encoding="utf-8"?><roblox version="4"><Item class="Workspace" referent="RBXWorkspace"><Properties><string name="Name">Workspace</string></Properties>'+roots+'</Item></roblox>'
}
exportXML=proExportXML;

})();