(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const initial=[{id:"spawn",name:"SpawnLocation",type:"SpawnLocation",position:[0,1,0],rotation:[0,0,0],size:[2,1,2],color:"#22c55e",anchored:true,canCollide:true},{id:"part",name:"Part",type:"Part",position:[0,0,0],rotation:[0,0,0],size:[8,1,8],color:"#64748b",anchored:true,canCollide:true},{id:"platform",name:"Platform",type:"Part",position:[0,3,-7],rotation:[0,0,0],size:[6,1,4],color:"#8b5cf6",anchored:true,canCollide:true}];
const S={nodes:structuredClone(initial),selected:"part",tool:"select",panel:"properties",playing:false,project:"Meu Primeiro Jogo"};
let scene,camera,renderer,ray,pointer,target,theta=.62,phi=.92,radius=27,orbit=false,lx=0,ly=0,meshes=new Map();
function status(t){$("#status").textContent=t;$("#footerStatus").textContent=t}
function cur(){return S.nodes.find(n=>n.id===S.selected)}
function save(){localStorage.setItem("studio-lite",JSON.stringify({name:S.project,nodes:S.nodes}));status("Salvo localmente")}
function add(type="Part"){let n={id:uid(),name:type==="Script"?"Script":type==="Folder"?"Folder":type,type,position:[0,2,0],rotation:[0,0,0],size:type==="SpawnLocation"?[2,1,2]:[4,1,4],color:type==="SpawnLocation"?"#22c55e":"#3b82f6",anchored:true,canCollide:type==="Part"};if(type==="Script")n.script='-- Novo Script\n\nprint("Hello from Studio Lite!")';S.nodes.push(n);S.selected=n.id;render();status(type+" criado");if(type==="Script")script(n.id)}
function duplicate(){let n=cur();if(!n)return;let d=structuredClone(n);d.id=uid();d.name=n.name+" Copy";d.position[0]+=2;d.position[2]+=2;S.nodes.push(d);S.selected=d.id;render();status("Objeto duplicado")}
function remove(){let n=cur();if(!n||n.id==="spawn"){status("SpawnLocation não pode ser removido");return}S.nodes=S.nodes.filter(x=>x.id!==n.id);S.selected=S.nodes[0]?.id||null;render();status("Objeto removido")}
function transform(t){let n=cur();if(!n)return;if(t==="move")n.position[0]+=1;if(t==="rotate")n.rotation[1]+=15;if(t==="scale"){n.size[0]+=1;n.size[2]+=1}S.tool=t;render();status(t==="move"?"Movido 1 stud":t==="rotate"?"Rotacionado 15°":"Escalado")}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color("#030303");camera=new THREE.PerspectiveCamera(55,1,.1,1000);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$("#canvas").appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x101010,1.8));let l=new THREE.DirectionalLight(0xffffff,1.5);l.position.set(8,20,10);scene.add(l);scene.add(new THREE.GridHelper(60,60,0x252525,0x111111));target=new THREE.Vector3(0,1,0);ray=new THREE.Raycaster();pointer=new THREE.Vector2();resize();sync();renderer.domElement.oncontextmenu=e=>e.preventDefault();renderer.domElement.addEventListener("pointerdown",down);renderer.domElement.addEventListener("pointermove",move);renderer.domElement.addEventListener("pointerup",()=>orbit=false);renderer.domElement.addEventListener("wheel",wheel,{passive:false});addEventListener("resize",resize);loop()}
function resize(){let e=$("#canvas");camera.aspect=e.clientWidth/e.clientHeight;camera.updateProjectionMatrix();renderer.setSize(e.clientWidth,e.clientHeight,false)}
function sync(){camera.position.set(target.x+radius*Math.sin(phi)*Math.sin(theta),target.y+radius*Math.cos(phi),target.z+radius*Math.sin(phi)*Math.cos(theta));camera.lookAt(target)}
function down(e){if(e.button===1||e.button===2){orbit=true;lx=e.clientX;ly=e.clientY;return}let r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);let h=ray.intersectObjects([...meshes.values()])[0];if(h?.object.userData.id){S.selected=h.object.userData.id;render();status("Objeto selecionado")}}
function move(e){if(!orbit)return;theta-=(e.clientX-lx)*.008;phi=Math.max(.12,Math.min(Math.PI-.12,phi-(e.clientY-ly)*.008));lx=e.clientX;ly=e.clientY;sync()}
function wheel(e){e.preventDefault();radius=Math.max(3,Math.min(100,radius*(e.deltaY>0?1.08:.92)));sync()}
function loop(){renderer.render(scene,camera);requestAnimationFrame(loop)}
function updateMeshes(){let ids=new Set();S.nodes.forEach(n=>{ids.add(n.id);let m=meshes.get(n.id);if(!m){m=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({roughness:.72,metalness:.08}));m.userData.id=n.id;scene.add(m);meshes.set(n.id,m)}m.position.set(...n.position);m.rotation.set(n.rotation[0]*Math.PI/180,n.rotation[1]*Math.PI/180,n.rotation[2]*Math.PI/180);m.scale.set(...n.size);m.material.color.set(n.color||"#777");m.material.emissive.set(n.id===S.selected?"#444":"#000");m.material.emissiveIntensity=n.id===S.selected?.3:0;m.visible=!["Folder","Script"].includes(n.type)});for(let [id,m] of meshes)if(!ids.has(id)){scene.remove(m);m.geometry.dispose();m.material.dispose();meshes.delete(id)}}
function tree(){let t=$("#tree");t.innerHTML='<div class="root">⌄ <b>Workspace</b></div>';S.nodes.forEach(n=>{let b=document.createElement("button");b.className="tree-row"+(n.id===S.selected?" selected":"");b.innerHTML="<span>"+(n.type==="Script"?"◇":n.type==="Folder"?"▱":"◈")+"</span><span>"+esc(n.name)+"</span><span class=type>"+n.type+"</span>";b.onclick=()=>{S.selected=n.id;render()};t.appendChild(b)});["Lighting","ReplicatedStorage","ServerScriptService","StarterGui"].forEach(x=>{let d=document.createElement("div");d.className="root muted";d.textContent="› "+x;t.appendChild(d)})}
function panel(){let p=$("#panel");$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.panel===S.panel));if(S.panel==="toolbox"){p.innerHTML='<div class=panel><input class=search placeholder="⌕ Pesquisar assets"><div class=section-title>ASSETS</div></div>';["Part","Folder","Script","SpawnLocation"].forEach(x=>{let b=document.createElement("button");b.className="asset";b.innerHTML='<span class=asset-icon>◈</span><span><b>'+x+'</b><small>Studio object</small></span><strong>＋</strong>';b.onclick=()=>add(x);p.firstChild.appendChild(b)});return}let n=cur();if(!n){p.innerHTML='<div class=panel><div class=empty>Selecione um objeto</div></div>';return}p.innerHTML='<div class=panel><div class=object><div class=object-icon>◈</div><div><b>'+esc(n.name)+'</b><small>'+n.type+'</small></div></div></div>';p=p.firstChild;section(p,"TRANSFORM");vector(p,"Position",n.position,v=>{n.position=v;updateMeshes()});vector(p,"Rotation",n.rotation,v=>{n.rotation=v;updateMeshes()});vector(p,"Size",n.size,v=>{n.size=v;updateMeshes()});if(n.type!=="Script"){section(p,"APPEARANCE");let d=document.createElement("div");d.className="field";d.innerHTML='<span>Material</span><select><option>Plastic</option><option>Metal</option><option>Wood</option><option>Glass</option></select>';p.appendChild(d);d=document.createElement("div");d.className="field";d.innerHTML='<span>Color</span><input type=color value="'+n.color+'">';d.querySelector("input").oninput=e=>{n.color=e.target.value;updateMeshes()};p.appendChild(d)}if(n.type==="Script"){let b=document.createElement("button");b.className="wide primary";b.textContent="Abrir Script Editor";b.onclick=()=>script(n.id);p.appendChild(b)}section(p,"BEHAVIOR");toggle(p,"Anchored",n.anchored,v=>n.anchored=v);toggle(p,"CanCollide",n.canCollide,v=>n.canCollide=v)}
function section(p,t){let d=document.createElement("div");d.className="section-title";d.textContent=t;p.appendChild(d)}
function vector(p,t,a,fn){let d=document.createElement("div");d.className="vector";d.innerHTML="<span>"+t+"</span><div></div>";a.forEach((v,i)=>{let x=document.createElement("input");x.value=v;x.onchange=()=>{let b=[...a];b[i]=Number(x.value)||0;fn(b);panel()};d.lastChild.appendChild(x)});p.appendChild(d)}
function toggle(p,t,v,fn){let d=document.createElement("div");d.className="toggle";d.innerHTML="<span>"+t+"</span><button class=switch "+(v?"on":"")+"><i></i></button>";d.lastChild.onclick=()=>{fn(!v);panel()};p.appendChild(d)}
function render(){tree();panel();updateMeshes()}
function focus(){let n=cur();if(n){target.set(...n.position);radius=12;sync()}}
function script(id){let n=S.nodes.find(x=>x.id===id),bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=script-window><div class=script-head><b>◇ '+esc(n.name)+'</b><div><button id=ss class=primary>Salvar</button> <button id=sc>×</button></div></div><div class=editor><div class=lines id=lines></div><textarea class=script-area id=st spellcheck=false></textarea></div><div class=script-foot>Luau • UTF-8 • <span id=lc>0</span> linhas</div></div>';$("#modalRoot").appendChild(bg);let ta=$("#st"),ln=$("#lines");ta.value=n.script||"-- Novo Script\n";let sync=()=>{ln.innerHTML=ta.value.split("\n").map((_,i)=>i+1).join("<br>");$("#lc").textContent=ta.value.split("\n").length};sync();ta.oninput=sync;$("#sc").onclick=()=>bg.remove();$("#ss").onclick=()=>{n.script=ta.value;bg.remove();save();status("Script salvo")}}
function publish(){let bg=document.createElement("div");bg.className="modal-bg";bg.innerHTML='<div class=modal><div class=modal-head><h2>Publicar no Roblox</h2><button id=x>×</button></div><p>Esta versão é 100% HTML/CSS/JavaScript. Para publicar com Roblox Open Cloud, use um backend PHP seguro. A API Key nunca deve ficar no JavaScript.</p><input placeholder="Universe ID"><input placeholder="Place ID"><div class=modal-actions><button id=c>Fechar</button></div></div>';$("#modalRoot").appendChild(bg);$("#x").onclick=$("#c").onclick=()=>bg.remove()}
async function file(f){if(!f)return;status("Importando…");let name=f.name.toLowerCase();if(name.endsWith(".json")){try{let d=JSON.parse(await f.text());S.nodes=d.nodes||d;S.selected=S.nodes[0]?.id;render();status("Projeto importado")}catch{status("JSON inválido")}return}if(name.endsWith(".rbxl")){status("RBXL binário: use conversor no backend");return}try{let doc=new DOMParser().parseFromString(await f.text(),"application/xml"),els=[...doc.querySelectorAll("Item")].filter(e=>["Part","SpawnLocation","WedgePart","CornerWedgePart","MeshPart"].includes(e.getAttribute("class")));let out=els.map((e,i)=>{let prop=n=>e.querySelector('Properties > *[name="'+n+'"]'),txt=n=>prop(n)?.textContent||"",vec=n=>{let z=prop(n);return z?[+z.querySelector("X")?.textContent||0,+z.querySelector("Y")?.textContent||0,+z.querySelector("Z")?.textContent||0]:[0,0,0]};return{id:uid(),name:txt("Name")||"Part "+(i+1),type:e.getAttribute("class"),position:vec("CFrame"),rotation:[0,0,0],size:vec("size").map(v=>v||1),color:"#64748b",anchored:txt("Anchored")==="true",canCollide:txt("CanCollide")!=="false"}});if(out.length){S.nodes=out;S.selected=out[0].id;render();status(out.length+" objetos importados")}else status("Nenhum objeto compatível")}catch{status("RBXLX inválido")}}
function exportJSON(){let b=new Blob([JSON.stringify({name:S.project,nodes:S.nodes},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(S.project||"studio-project").replace(/[^a-z0-9_-]/gi,"-")+".json";a.click();URL.revokeObjectURL(a.href);status("Projeto exportado")}
$("#saveBtn").onclick=save;$("#duplicateBtn").onclick=duplicate;$("#deleteBtn").onclick=remove;$("#focusBtn").onclick=focus;$("#publishBtn").onclick=publish;$("#exportBtn").onclick=exportJSON;$("#importBtn").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>file(e.target.files[0]);$("#projectName").onchange=e=>{S.project=e.target.value;save()};$("#playBtn").onclick=()=>{S.playing=!S.playing;$("#playBadge").classList.toggle("on",S.playing);$("#playBtn").textContent=S.playing?"■ Stop":"▶ Play";status(S.playing?"Play Mode iniciado":"Play Mode encerrado")};
document.addEventListener("click",e=>{let a=e.target.closest("[data-add]");if(a)add(a.dataset.add);let t=e.target.closest("[data-tool]");if(t){S.tool=t.dataset.tool;$$(".tool").forEach(x=>x.classList.toggle("active",x===t));if(S.tool!=="select")transform(S.tool)}let p=e.target.closest("[data-panel]");if(p){S.panel=p.dataset.panel;panel()}});
addEventListener("keydown",e=>{if(/input|textarea|select/i.test(e.target.tagName))return;if(e.key==="Delete"||e.key==="Backspace")remove();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"){e.preventDefault();duplicate()}if(e.key.toLowerCase()==="w")transform("move");if(e.key.toLowerCase()==="e")transform("rotate");if(e.key.toLowerCase()==="r")transform("scale");if(e.key.toLowerCase()==="f")focus()});
try{let d=JSON.parse(localStorage.getItem("studio-lite"));if(d?.nodes){S.nodes=d.nodes;S.project=d.name||S.project;$("#projectName").value=S.project}}catch{}init();render();
})();