(()=>{"use strict";
const E=window.StudioLiteExtra;if(!E)return;
const C=()=>window.StudioLiteCore||{};const S=()=>C().S||window.S;const N=()=>S()?.nodes||[];
const sel=()=>{const s=S(),ids=new Set(s?.selectedIds||[]);return N().filter(n=>ids.has(n.id))};
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now();
const save=()=>C().save?.(false),render=()=>C().render?.(),commit=()=>C().commit?.();
const mut=fn=>{if(!S())return false;commit();const r=fn();render();save();return r===undefined?true:r};
const cp=x=>{try{return JSON.parse(JSON.stringify(x))}catch{return x}};
const p=n=>Array.isArray(n?.position)?n.position:[0,0,0];
const r=n=>Array.isArray(n?.rotation)?n.rotation:[0,0,0];
const z=n=>Array.isArray(n?.size)?n.size:[1,1,1];
const axis=a=>({x:0,y:1,z:2}[String(a||"x").toLowerCase()]??0);
const desc=id=>{const o=[],seen=new Set([id]);let go=true;while(go){go=false;for(const n of N())if(n.parent&&seen.has(n.parent)&&!seen.has(n.id)){seen.add(n.id);o.push(n);go=true}}return o};
Object.assign(E,{
moveAxis(a="x",d=1){const i=axis(a);return mut(()=>sel().forEach(n=>{n.position=[...p(n)];n.position[i]+=Number(d)||0}))},
rotateAxis(a="y",d=15){const i=axis(a);return mut(()=>sel().forEach(n=>{n.rotation=[...r(n)];n.rotation[i]+=Number(d)||0}))},
scaleAxis(a="x",k=1.1){const i=axis(a);return mut(()=>sel().forEach(n=>{n.size=[...z(n)];n.size[i]=Math.max(.1,n.size[i]*(Number(k)||1))}))},
mirrorPosition(a="x"){const i=axis(a);return mut(()=>sel().forEach(n=>{n.position=[...p(n)];n.position[i]*=-1}))},
mirrorRotation(a="x"){const i=axis(a);return mut(()=>sel().forEach(n=>{n.rotation=[...r(n)];n.rotation[i]*=-1}))},
fitSizeToSelection(){const a=sel();if(!a.length)return false;const mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];a.forEach(n=>p(n).forEach((v,i)=>{mn[i]=Math.min(mn[i],v-z(n)[i]/2);mx[i]=Math.max(mx[i],v+z(n)[i]/2)}));return{min:mn,max:mx,size:mx.map((v,i)=>v-mn[i])}},
distributeAxis(a="x"){const a1=sel().slice().sort((x,y)=>p(x)[axis(a)]-p(y)[axis(a)]);if(a1.length<3)return false;const i=axis(a),lo=p(a1[0])[i],hi=p(a1.at(-1))[i],step=(hi-lo)/(a1.length-1);return mut(()=>a1.forEach((n,j)=>{n.position=[...p(n)];n.position[i]=lo+step*j}))},
alignMin(a="x"){const i=axis(a),v=Math.min(...sel().map(n=>p(n)[i]));return mut(()=>sel().forEach(n=>{n.position=[...p(n)];n.position[i]=v}))},
alignMax(a="x"){const i=axis(a),v=Math.max(...sel().map(n=>p(n)[i]));return mut(()=>sel().forEach(n=>{n.position=[...p(n)];n.position[i]=v}))},
setPositionComponent(a="x",v=0){const i=axis(a);return mut(()=>sel().forEach(n=>{n.position=[...p(n)];n.position[i]=Number(v)||0}))},
setRotationComponent(a="y",v=0){const i=axis(a);return mut(()=>sel().forEach(n=>{n.rotation=[...r(n)];n.rotation[i]=Number(v)||0}))},
setSizeComponent(a="x",v=1){const i=axis(a);return mut(()=>sel().forEach(n=>{n.size=[...z(n)];n.size[i]=Math.max(.1,Number(v)||1)}))},
clampPosition(min=-100,max=100){return mut(()=>sel().forEach(n=>n.position=p(n).map(v=>Math.max(min,Math.min(max,v))))},
clampTransparency(min=0,max=1){return mut(()=>sel().forEach(n=>n.transparency=Math.max(min,Math.min(max,Number(n.transparency)||0))))},
toggleAnchored(){return mut(()=>sel().forEach(n=>n.anchored=!n.anchored)},
toggleVisible(){return mut(()=>sel().forEach(n=>n.visible=n.visible===false))},
toggleLocked(){return mut(()=>sel().forEach(n=>n.locked=!n.locked)},
toggleCollision(){return mut(()=>sel().forEach(n=>n.canCollide=!n.canCollide)},
toggleTouch(){return mut(()=>sel().forEach(n=>n.canTouch=!n.canTouch)},
toggleQuery(){return mut(()=>sel().forEach(n=>n.canQuery=!n.canQuery)},
toggleMassless(){return mut(()=>sel().forEach(n=>n.massless=!n.massless)},
setNameAll(name="Object"){return mut(()=>sel().forEach(n=>n.name=String(name)))},
replaceNames(a="",b=""){return mut(()=>N().forEach(n=>n.name=String(n.name||"").split(a).join(b)))},
numberNames(prefix="Object"){return mut(()=>N().forEach((n,i)=>n.name=prefix+" "+(i+1)))},
sortChildrenByName(id){const kids=N().filter(n=>n.parent===id).sort((a,b)=>String(a.name).localeCompare(String(b.name)));return mut(()=>{let k=0;N().forEach(n=>{if(n.parent===id)n.name=kids[k++]?.name||n.name})})},
duplicateTree(){const roots=sel();if(!roots.length)return false;return mut(()=>{const map=new Map();const all=roots.flatMap(x=>[x,...desc(x.id)]);all.forEach(x=>{const y=cp(x);y.id=uid();y.name=(x.name||x.type)+" Copy";map.set(x.id,y.id);N().push(y)});all.forEach(x=>{const y=N().find(n=>n.id===map.get(x.id));if(y)y.parent=map.get(x.parent)||x.parent||null})})},
cloneToParent(parentId){const target=N().find(n=>n.id===parentId);if(!target)return false;return mut(()=>sel().forEach(x=>{const y=cp(x);y.id=uid();y.name=(x.name||x.type)+" Copy";y.parent=target.id;N().push(y)}))},
clearSelection(){const s=S();s.selectedIds=[];s.selected=null;render();return true},
selectChildren(id){const x=id||sel()[0]?.id,s=S();s.selectedIds=N().filter(n=>n.parent===x).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectDescendants(id){const x=id||sel()[0]?.id,s=S();s.selectedIds=desc(x).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectSiblings(id){const x=N().find(n=>n.id===(id||sel()[0]?.id)),s=S();s.selectedIds=N().filter(n=>n.parent===(x?.parent||null)).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectRootObjects(){const s=S();s.selectedIds=N().filter(n=>!n.parent).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectVisible(){return E.selectByVisibility(true)},
selectHidden(){return E.selectByVisibility(false)},
selectScripts(){const s=S();s.selectedIds=N().filter(n=>/Script$/.test(n.type)).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectParts(){const s=S();s.selectedIds=N().filter(n=>/Part$/.test(n.type)||["MeshPart","UnionOperation"].includes(n.type)).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectLights(){const s=S();s.selectedIds=N().filter(n=>/Light$/.test(n.type)).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectGui(){const s=S();s.selectedIds=N().filter(n=>/Gui$/.test(n.type)).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
setParentKeepWorld(id){const par=N().find(n=>n.id===id);if(!par)return false;return mut(()=>sel().forEach(n=>n.parent=par.id))},
clearParents(){return mut(()=>N().forEach(n=>n.parent=null))},
moveToRoot(){return mut(()=>sel().forEach(n=>n.parent=null))},
renameChildren(id,prefix="Child"){return mut(()=>N().filter(n=>n.parent===(id||sel()[0]?.id)).forEach((n,i)=>n.name=prefix+" "+(i+1)))},
addChildrenFolders(name="Folder"){const a=sel();return mut(()=>a.forEach(p=>N().push({id:uid(),type:"Folder",name,parent:p.id,position:[0,0,0],size:[1,1,1],visible:true})))},
addChildrenScripts(){const a=sel();return mut(()=>a.forEach(p=>N().push({id:uid(),type:"Script",name:"Script",parent:p.id,position:[0,0,0],size:[1,1,1],visible:true,script:"print(\"Hello from Roblox!\")",language:"luau"})))},
addChildrenParts(){const a=sel();return mut(()=>a.forEach(p=>N().push({id:uid(),type:"Part",name:"Part",parent:p.id,position:[0,0,0],size:[2,2,2],visible:true,anchored:true,canCollide:true,color:"#3b82f6",material:"Plastic"})))},
addChildrenLights(){const a=sel();return mut(()=>a.forEach(p=>N().push({id:uid(),type:"PointLight",name:"PointLight",parent:p.id,position:[0,2,0],size:[1,1,1],visible:true})))},
clearAllAttributes(){return mut(()=>N().forEach(n=>n.attributes={}))},
copyAttributesFromFirst(){const a=sel();if(a.length<2)return false;const attrs=cp(a[0].attributes||{});return mut(()=>a.slice(1).forEach(n=>n.attributes=cp(attrs)))},
copyPropertyFromFirst(k){const a=sel();if(a.length<2)return false;const v=cp(a[0][k]);return mut(()=>a.slice(1).forEach(n=>n[k]=cp(v)))},
copyTransformFromFirst(){const a=sel();if(a.length<2)return false;const q=a[0];return mut(()=>a.slice(1).forEach(n=>{n.position=cp(p(q));n.rotation=cp(r(q));n.size=cp(z(q))}))},
resetPosition(){return mut(()=>sel().forEach(n=>n.position=[0,0,0]))},
resetRotation(){return mut(()=>sel().forEach(n=>n.rotation=[0,0,0]))},
resetSize(){return mut(()=>sel().forEach(n=>n.size=[2,2,2]))},
setPivotToAverage(){const a=sel();if(!a.length)return false;const c=[0,1,2].map(i=>a.reduce((q,n)=>q+p(n)[i],0)/a.length);return mut(()=>a.forEach(n=>n.pivot=cp(c)))},
setCustomProperty(k,v){return E.setProperty(k,v)},
deleteByType(t){const ids=new Set(N().filter(n=>n.type===t).map(n=>n.id));return mut(()=>S().nodes=N().filter(n=>!ids.has(n.id)))},
deleteHidden(){return mut(()=>S().nodes=N().filter(n=>n.visible!==false))},
deleteLocked(){return mut(()=>S().nodes=N().filter(n=>n.locked!==true))},
deleteEmptyFolders(){const ids=new Set(N().filter(n=>n.type==="Folder"&&!N().some(x=>x.parent===n.id)).map(n=>n.id));return mut(()=>S().nodes=N().filter(n=>!ids.has(n.id)))},
deleteEmptyModels(){const ids=new Set(N().filter(n=>n.type==="Model"&&!N().some(x=>x.parent===n.id)).map(n=>n.id));return mut(()=>S().nodes=N().filter(n=>!ids.has(n.id)))},
repairDuplicateNames(){return mut(()=>{const map=new Map();N().forEach(n=>{const k=n.parent+"|"+n.name;const c=(map.get(k)||0)+1;map.set(k,c);if(c>1)n.name=n.name+" ("+c+")"})})},
repairDuplicateIds(){return mut(()=>{const seen=new Set();N().forEach(n=>{if(seen.has(n.id))n.id=uid();seen.add(n.id)})})},
repairScripts(){return mut(()=>N().filter(n=>/Script$/.test(n.type)).forEach(n=>{n.language??="luau";n.script??=""}))},
repairVisualDefaults(){return mut(()=>N().forEach(n=>{if(n.visible===undefined)n.visible=true;if(n.transparency===undefined)n.transparency=0;if(n.color===undefined)n.color="#3b82f6";if(n.material===undefined)n.material="Plastic"}))},
validateHierarchy(){const ids=new Set(N().map(n=>n.id)),bad=N().filter(n=>n.parent&&!ids.has(n.parent));return{ok:bad.length===0,orphans:bad.map(cp)}},
validateDuplicates(){const m=new Map(),dups=[];N().forEach(n=>{if(m.has(n.id))dups.push(n);m.set(n.id,true)});return{ok:!dups.length,duplicates:dups.map(cp)}},
validateScripts(){return{ok:N().every(n=>!/Script$/.test(n.type)||typeof n.script==="string"),invalid:N().filter(n=>/Script$/.test(n.type)&&typeof n.script!=="string").map(cp)}},
validateProperties(){const bad=N().filter(n=>!n.id||!n.type||!n.name);return{ok:!bad.length,invalid:bad.map(cp)}},
projectReport(){return{stats:E.sceneStats(),hierarchy:E.validateHierarchy(),scripts:E.validateScripts(),properties:E.validateProperties()}},
exportProjectCompact(){const data=JSON.stringify(N());const b=new Blob([data],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="studio-lite-project.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);return true},
copyProjectJSON(){return navigator.clipboard?.writeText(JSON.stringify(N(),null,2)).then(()=>true).catch(()=>false)},
saveNow(){C().save?.(true);return true},
refreshEditor(){render();return true},
undoLast(){C().undo?.();return true},
redoLast(){C().redo?.();return true},
openExplorerPanel(){return E.openExplorer?.()},
openPropertiesPanel(){return E.openProperties?.()},
openCodePanel(){return E.openCodeStudio?.()},
randomizeColors(){return mut(()=>N().filter(n=>n.color!==undefined).forEach(n=>n.color="#"+Math.floor(Math.random()*16777215).toString(16).padStart(6,"0")))},
randomizeMaterials(list=["Plastic","Wood","Metal","Glass","Neon"]){return mut(()=>N().forEach(n=>{n.material=list[Math.floor(Math.random()*list.length)]}))},
makeNeon(){return E.setMaterial("Neon")},
makeGlass(){return E.setMaterial("Glass")},
makeMetal(){return E.setMaterial("Metal")},
makePlastic(){return E.setMaterial("Plastic")},
hideChildren(){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.visible=false))},
showChildren(){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.visible=true))},
lockChildren(){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.locked=true))},
unlockChildren(){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.locked=false))},
anchorChildren(){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.anchored=true))},
unanchorChildren(){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.anchored=false))},
setChildrenTransparency(v=.5){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.transparency=Math.max(0,Math.min(1,Number(v)||0))))},
setChildrenMaterial(m="Plastic"){return mut(()=>sel().forEach(p=>N().filter(n=>n.parent===p.id).forEach(n=>n.material=m))},
countChildrenByType(t,id){return N().filter(n=>n.parent===(id||sel()[0]?.id)&&n.type===t).length},
countObjectsAtDepth(d=0){return N().filter(n=>{let x=n,c=0,seen=new Set();while(x?.parent&&!seen.has(x.parent)){seen.add(x.parent);x=N().find(q=>q.id===x.parent);if(x)c++}return c===Number(d)}).length},
getAllTypes(){return [...new Set(N().map(n=>n.type))].sort()},
getAllMaterials(){return [...new Set(N().map(n=>n.material).filter(Boolean))].sort()},
getAllNames(){return N().map(n=>n.name)},
getProjectSize(){return JSON.stringify(N()).length},
getMaxDepth(){return Math.max(0,...N().map(n=>E.getTreeDepth(n.id)))},
getBoundingBox(){return E.fitSizeToSelection?.()},
selectProperty(k,v){const s=S();s.selectedIds=N().filter(n=>n[k]===v).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
selectAttribute(k,v){const s=S();s.selectedIds=N().filter(n=>n.attributes?.[k]===v).map(n=>n.id);s.selected=s.selectedIds[0]||null;render();return s.selectedIds.length},
setAttributeAll(k,v){return mut(()=>N().forEach(n=>{n.attributes??={};n.attributes[k]=v}))},
removeAttributeAll(k){return mut(()=>N().forEach(n=>{if(n.attributes)delete n.attributes[k]}))},
setScriptLanguage(lang="luau"){return mut(()=>sel().filter(n=>/Script$/.test(n.type)).forEach(n=>n.language=lang))},
appendCommentToScripts(comment="-- Studio Lite"){return mut(()=>N().filter(n=>/Script$/.test(n.type)).forEach(n=>n.script=String(n.script||"")+ "\n"+comment+"\n"))},
duplicateSelectedNames(){return E.duplicateOffset?.(2,"x")},
quickCleanup(){E.repairOrphans?.();E.repairNames?.();E.repairDefaults?.();E.repairScripts?.();return true}
});
window.StudioLiteExtraMeta={moreFunctions:Object.keys({
moveAxis:1,rotateAxis:1,scaleAxis:1,mirrorPosition:1,mirrorRotation:1,fitSizeToSelection:1,distributeAxis:1,alignMin:1,alignMax:1,setPositionComponent:1,setRotationComponent:1,setSizeComponent:1,clampPosition:1,clampTransparency:1,toggleAnchored:1,toggleVisible:1,toggleLocked:1,toggleCollision:1,toggleTouch:1,toggleQuery:1,toggleMassless:1,setNameAll:1,replaceNames:1,numberNames:1,sortChildrenByName:1,duplicateTree:1,cloneToParent:1,clearSelection:1,selectChildren:1,selectDescendants:1,selectSiblings:1,selectRootObjects:1,selectVisible:1,selectHidden:1,selectScripts:1,selectParts:1,selectLights:1,selectGui:1,setParentKeepWorld:1,clearParents:1,moveToRoot:1,renameChildren:1,addChildrenFolders:1,addChildrenScripts:1,addChildrenParts:1,addChildrenLights:1,clearAllAttributes:1,copyAttributesFromFirst:1,copyPropertyFromFirst:1,copyTransformFromFirst:1,resetPosition:1,resetRotation:1,resetSize:1,setPivotToAverage:1,setCustomProperty:1,deleteByType:1,deleteHidden:1,deleteLocked:1,deleteEmptyFolders:1,deleteEmptyModels:1,repairDuplicateNames:1,repairDuplicateIds:1,repairScripts:1,repairVisualDefaults:1,validateHierarchy:1,validateDuplicates:1,validateScripts:1,validateProperties:1,projectReport:1,exportProjectCompact:1,copyProjectJSON:1,saveNow:1,refreshEditor:1,undoLast:1,redoLast:1,openExplorerPanel:1,openPropertiesPanel:1,openCodePanel:1,randomizeColors:1,randomizeMaterials:1,makeNeon:1,makeGlass:1,makeMetal:1,makePlastic:1,hideChildren:1,showChildren:1,lockChildren:1,unlockChildren:1,anchorChildren:1,unanchorChildren:1,setChildrenTransparency:1,setChildrenMaterial:1,countChildrenByType:1,countObjectsAtDepth:1,getAllTypes:1,getAllMaterials:1,getAllNames:1,getProjectSize:1,getMaxDepth:1,getBoundingBox:1,selectProperty:1,selectAttribute:1,setAttributeAll:1,removeAttributeAll:1,setScriptLanguage:1,appendCommentToScripts:1,duplicateSelectedNames:1,quickCleanup:1}).length};
})();
